openapi: 3.0.0
info:
  title: Hapi test
  version: 1.0.0
servers:
  - url: http://localhost:3000/api
    description: Api
paths:
  /satellite:
    post:
      400:
        description: Petición invalida
      404:
        description: Uno o mas satelites no existen
      200:
        description: Success
    get:
      200:
          description: Success
